# Commit API Requests

### Create a commit in a repository
POST http://localhost:4000/commit-api/69b79e1eeea7d84955bfca4d/commits
Content-Type: application/json

{
  "message": "Committing",
  "commitHash": "lucy123"
}

### Get all commits in a repository
GET http://localhost:4000/commit-api/69b79e1eeea7d84955bfca4d/commits

### Get a specific commit
GET http://localhost:4000/commit-api/commit/69b8d77b9b60bbc67884fce9


### Delete a commit
DELETE http://localhost:4000/commit-api/commit/69b8d77b9b60bbc67884fce9